export NNN_PLUG="d:-dragdrop;j:autojump;i:-imgview;p:-preview-tui"
export NNN_PREVIEWDIR="/tmp"
export SUDO_EDITOR="nvim"
export EDITOR="nvim"
export READER="zathura"
BLK="0B" CHR="0B" DIR="04" EXE="06" REG="00" HARDLINK="06" SYMLINK="06" MISSING="00" ORPHAN="09" FIFO="06" SOCK="0B" OTHER="06"
export NNN_FCOLORS="$BLK$CHR$DIR$EXE$REG$HARDLINK$SYMLINK$MISSING$ORPHAN$FIFO$SOCK$OTHER"
export MANPAGER="nvim +Man!"
