#!/bin/bash
# bash initialization script

if [ -z "$SSH_AUTH_SOCK" ]; then
    eval 'ssh-agent -s' > /dev/null
fi

for f in $(find ~/.ssh -name id_rsa); do
    ssh-add -q $f
done

interserver_mountpoint=/home/jakov/SSH/interserver;

if ! df -h 2>&1 | grep -q "$interserver_mountpoint"; then
    echo "Mounting ${interserver_mountpoint##/}"
    sshfs -p 36404 jakov@162.250.127.156:/home/jakov "$interserver_mountpoint"
fi

