[colors.primary]
background = "#1d1d1d"
foreground = "#f3fef9"

[colors.search.focused_match]
background = "#ff7050"
foreground = "#000000"

[colors.search.matches]
background = "#000000"
foreground = "#ff7050"

[cursor.style]
blinking = "On"
shape = "Block"

[font]
size = 12.0

[font.bold]
family = "Ubuntu Mono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Ubuntu Mono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Ubuntu Mono Nerd Font"
style = "Italic"

[font.normal]
family = "Ubuntu Mono Nerd Font"
style = "Regular"

[shell]
program = "/bin/tmux"

[window]
decorations = "Full"
dynamic_title = true
opacity = 0.85
title = "terminal"
