[colors.primary]
background = "#2e3440"
foreground = "#f3fef9"

[colors.search.focused_match]
background = "#bf616a"
foreground = "#d8dee9"

[colors.search.matches]
background = "#8fbcbb"
foreground = "#d8dee9"

[cursor.style]
blinking = "Always"
shape = "Block"

[font]
size = 12.0

[font.bold]
family = "Ubuntu Mono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Ubuntu Mono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Ubuntu Mono Nerd Font"
style = "Italic"

[font.normal]
family = "Ubuntu Mono Nerd Font"
style = "Regular"

[terminal.shell]
program = "/bin/tmux"

[window]
decorations = "Full"
dynamic_title = true
opacity = 0.85
title = "terminal"

[terminal]
